export const slots = [
  {
    day: "Today",
    avl: 12,
    morning: [
      { time: "07:30 AM", avl: false },
      { time: "09:00 AM", avl: false },
      { time: "10:30 AM", avl: true },
      { time: "12:00 PM", avl: false },
      { time: "01:30 PM", avl: true },
    ],
    afternoon: [
      { time: "12:30 PM", avl: false },
      { time: "02:00 PM", avl: true },
      { time: "03:30 PM", avl: false },
      { time: "05:00 PM", avl: true },
      { time: "06:30 PM", avl: true },
    ],
    evening: [
      { time: "05:30 PM", avl: false },
      { time: "07:00 PM", avl: false },
      { time: "08:30 PM", avl: false },
      { time: "10:00 PM", avl: false },
      { time: "11:30 PM", avl: true },
    ],
  },
  {
    day: "Tomorrow",
    avl: 10,
    morning: [
      { time: "07:30 AM", avl: true },
      { time: "09:00 AM", avl: false },
      { time: "10:30 AM", avl: false },
      { time: "12:00 PM", avl: true },
      { time: "01:30 PM", avl: false },
    ],
    afternoon: [
      { time: "12:30 PM", avl: true },
      { time: "02:00 PM", avl: false },
      { time: "03:30 PM", avl: false },
      { time: "05:00 PM", avl: false },
      { time: "06:30 PM", avl: true },
    ],
    evening: [
      { time: "05:30 PM", avl: false },
      { time: "07:00 PM", avl: true },
      { time: "08:30 PM", avl: false },
      { time: "10:00 PM", avl: true },
      { time: "11:30 PM", avl: true },
    ],
  },
  {
    day: "2024-12-27",
    avl: 24,
    morning: [
      { time: "07:30 AM", avl: false },
      { time: "09:00 AM", avl: false },
      { time: "10:30 AM", avl: true },
      { time: "12:00 PM", avl: true },
      { time: "01:30 PM", avl: false },
    ],
    afternoon: [
      { time: "12:30 PM", avl: true },
      { time: "02:00 PM", avl: false },
      { time: "03:30 PM", avl: true },
      { time: "05:00 PM", avl: false },
      { time: "06:30 PM", avl: true },
    ],
    evening: [
      { time: "05:30 PM", avl: false },
      { time: "07:00 PM", avl: true },
      { time: "08:30 PM", avl: false },
      { time: "10:00 PM", avl: true },
      { time: "11:30 PM", avl: false },
    ],
  },
  {
    day: "2024-12-28",
    avl: 19,
    morning: [
      { time: "07:30 AM", avl: true },
      { time: "09:00 AM", avl: true },
      { time: "10:30 AM", avl: true },
      { time: "12:00 PM", avl: false },
      { time: "01:30 PM", avl: false },
    ],
    afternoon: [
      { time: "12:30 PM", avl: false },
      { time: "02:00 PM", avl: false },
      { time: "03:30 PM", avl: true },
      { time: "05:00 PM", avl: true },
      { time: "06:30 PM", avl: false },
    ],
    evening: [
      { time: "05:30 PM", avl: false },
      { time: "07:00 PM", avl: true },
      { time: "08:30 PM", avl: false },
      { time: "10:00 PM", avl: false },
      { time: "11:30 PM", avl: true },
    ],
  },
  {
    day: "2024-12-29",
    avl: 22,
    morning: [
      { time: "07:30 AM", avl: false },
      { time: "09:00 AM", avl: false },
      { time: "10:30 AM", avl: false },
      { time: "12:00 PM", avl: true },
      { time: "01:30 PM", avl: true },
    ],
    afternoon: [
      { time: "12:30 PM", avl: true },
      { time: "02:00 PM", avl: false },
      { time: "03:30 PM", avl: true },
      { time: "05:00 PM", avl: false },
      { time: "06:30 PM", avl: true },
    ],
    evening: [
      { time: "05:30 PM", avl: false },
      { time: "07:00 PM", avl: true },
      { time: "08:30 PM", avl: true },
      { time: "10:00 PM", avl: false },
      { time: "11:30 PM", avl: false },
    ],
  },
  {
    day: "2024-12-30",
    avl: 27,
    morning: [
      { time: "07:30 AM", avl: false },
      { time: "09:00 AM", avl: false },
      { time: "10:30 AM", avl: false },
      { time: "12:00 PM", avl: true },
      { time: "01:30 PM", avl: false },
    ],
    afternoon: [
      { time: "12:30 PM", avl: false },
      { time: "02:00 PM", avl: true },
      { time: "03:30 PM", avl: true },
      { time: "05:00 PM", avl: false },
      { time: "06:30 PM", avl: true },
    ],
    evening: [
      { time: "05:30 PM", avl: true },
      { time: "07:00 PM", avl: false },
      { time: "08:30 PM", avl: true },
      { time: "10:00 PM", avl: false },
      { time: "11:30 PM", avl: false },
    ],
  },
  {
    day: "2024-12-31",
    avl: 23,
    morning: [
      { time: "07:30 AM", avl: false },
      { time: "09:00 AM", avl: false },
      { time: "10:30 AM", avl: true },
      { time: "12:00 PM", avl: false },
      { time: "01:30 PM", avl: false },
    ],
    afternoon: [
      { time: "12:30 PM", avl: false },
      { time: "02:00 PM", avl: true },
      { time: "03:30 PM", avl: true },
      { time: "05:00 PM", avl: false },
      { time: "06:30 PM", avl: true },
    ],
    evening: [
      { time: "05:30 PM", avl: false },
      { time: "07:00 PM", avl: true },
      { time: "08:30 PM", avl: false },
      { time: "10:00 PM", avl: true },
      { time: "11:30 PM", avl: true },
    ],
  },
];
